name: "Push"

on: [push]

permissions:
  contents: read

jobs:
  Build-Docker:
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "./Dockerfile"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: rotoku/portfolio

      - name: Build and push Docker image
        uses: docker/build-push-action@6.9.0
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            rotoku/portfolio:${{ github.sha }}
            rotoku/portfolio:latest
          labels: ${{ steps.meta.outputs.labels }}

  Scan-Docker-Image:
    name: Scan Docker image for vulnerabilities
    runs-on: ubuntu-latest
    needs: Build-Docker
    permissions:
      security-events: write # Required to upload SARIF results
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.21.0
        with:
          image-ref: 'rotoku/portfolio:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
